"""Initial Migration

Revision ID: 07175439554f
Revises: 725d8dd870b4
Create Date: 2019-04-17 11:26:53.280837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07175439554f'
down_revision = '725d8dd870b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
