"""Initial Migration

Revision ID: 725d8dd870b4
Revises: 85ca4623cdcb
Create Date: 2019-04-16 14:56:00.980572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725d8dd870b4'
down_revision = '85ca4623cdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
